### ISSUE TITLE
服务器炸了

### ISSUE THREAD

**Issue by Az-eeeee** [CubeWhyMC/LunarClient-CN#12]

**Comment by Az-eeeee** [comment]
![7f002490a2e15e22.png](https://github.com/CubeWhyMC/LunarClient-CN/assets/80616593/c0fdc136-bea5-4831-94ae-f68c9f03df88)

**Comment by muskf** [comment]
早就恢复了,你没看到报错是read ECONERESET吗，这是用户自己的网络问题

**Comment by Az-eeeee** [comment]
就是测试Project的

**Comment by cubewhy** [comment]
muted
