### ISSUE TITLE
没有自动下载文件

### ISSUE THREAD

**Issue by lyjjl** [CubeWhyMC/LunarClient-CN#15]
额，有个问题，就是我启动启动器之后没有自动创建%USERPROFILE%/.cubewhy里面的任何文件，我手动补了javaagents、mods文件夹和config.json，但是依然不可用

**Comment by cubewhy** [comment]
你使用的是哪个版本的LUNARCN

**Comment by cubewhy** [comment]
请使用最新版（v1.0）进行启动，使用旧版本出现问题直接关issue

**Comment by lyjjl** [comment]
没错就是最新版



在 2023-08-21 22:04:58，"CubeWhy" ***@***.***> 写道：

请使用最新版（v1.0）进行启动，使用旧版本出现问题直接关issue

**Comment by cubewhy** [comment]
已弃用，请等待修复

**Comment by lyjjl** [comment]
1.0



在 2023-08-21 22:04:31，"CubeWhy" ***@***.***> 写道：

你使用的是哪个版本的LUNARCN
