### ISSUE TITLE
无法启动客户端？

### ISSUE THREAD

**Issue by PlayMcBKuwu** [CubeWhyMC/LunarClient-CN#20]
# 报错内容
> Lunar 客户端启动错误
> Short: 启动成功
> Description: 客户端启动成功
> Launcher Version: 2.16.1
> OS: win32 x64
> Game Module: lunar
> Game Version: /master
# 系统信息 / 启动器配置
- Windows 11 x64 22H2 22623.1028
- LunarCN 版本 1.0
- 游戏版本 1.8 OptiFine
# 大概描述
- 下了几个 Mods 和 Agents，关了又开，最后全关了依旧无法启动游戏
- LunarCN 提示启动了，但是任务管理器没有看到 Java.exe 或者 Javaw.exe

**Comment by cubewhy** [comment]
不提供任何日记等于闭眼开车

**Comment by PlayMcBKuwu** [comment]
> 不提供任何日记等于闭眼开车



> 不提供任何日记等于闭眼开车

- How can I find the log of LunarCN

**Comment by PlayMcBKuwu** [comment]
> 不提供任何日记等于闭眼开车

- 其次，里面说带有 LunarCN Loader 的版本可以装 Agents 和 Mods
- 不道是不是我用了原 OptiFine 的问题

**Comment by cubewhy** [comment]
launch.bat启动游戏

**Comment by cubewhy** [comment]
记得修改javaw -> java

**Comment by PlayMcBKuwu** [comment]
> 记得修改javaw -> java

- 解决了一半至少 Java.exe 启动了（
- ~~很明显我试图让原版新 Lunar 和 LunarCN 用同一个 .minecraft 文件夹~~
- ~~完全解决后我自己把这个 Issue 关掉（~~
- ~~这是我最 Low IQ 的一次~~

**Comment by PlayMcBKuwu** [comment]
> 所以解决了吗

- Zulu Java 启动一段时间后消失了
- ~~删除 JavaAgents 和 Mods 中~~

**Comment by PlayMcBKuwu** [comment]
> 所以解决了吗

- 工作了
# 总结
1. 不要试图和新原版 Lunar 同用一个 .minecraft 文件夹
2. ~~不要乱加 Agents~~
