### ISSUE TITLE
客户端启动错误

### ISSUE THREAD

**Issue by Klasd905614** [CubeWhyMC/LunarClient-CN#23]
Lunar 客户端启动错误
Short: 下载项目失败
Description: 下载项目失败 (https://cn-sy1.s3.rainyun.cn/lunarcn/cn0.0.2.jar): Response status was 403
Launcher Version: 2.16.1
OS: win32 x64
Game Module: lunar
Game Version: /master

**Comment by Klasd905614** [comment]
Error opening zip file or JAR manifest missing : C:\Users\Klasd\Desktop\1.0\resources\loader1.8.jar
Error occurred during initialization of VM
agent library failed to init: instrument

**Comment by cubewhy** [comment]
请使用新版本

**Comment by Klasd905614** [comment]
谢谢
