### ISSUE TITLE
game crashed

### ISSUE THREAD

**Issue by nbdexiaoyu** [CubeWhyMC/LunarClient-CN#25]
![image](https://github.com/CubeWhyMC/LunarClient-CN/assets/140889959/d98fd333-d201-4d90-8348-5a06352ad5ff)
lunar+forge

**Comment by cubewhy** [comment]
似乎切换语言时出现错误

**Comment by nbdexiaoyu** [comment]
?

**Comment by nbdexiaoyu** [comment]
![image](https://github.com/CubeWhyMC/LunarClient-CN/assets/140889959/297b1036-b615-4879-8a21-b60dc376fcaa)

**Comment by cubewhy** [comment]
有没有更详细的log
