### ISSUE TITLE
停止对Lunar官方的上报

### ISSUE THREAD

**Issue by muskf** [CubeWhyMC/LunarClient-CN#26]
lunar.jar中存在一些代码,会将游戏的各种数据报告到sentry,建议屏蔽
`public class CRHICIIOIIOIOIIOCOOICHCHC {
   private static final String OIRIROIROOHCORICHHHHORHRH = "https://49db0029d2304d69bd80986185f7fafd@o923049.ingest.sentry.io/6029559";
   private static final String OHHICOICHROCCHOHRCORRRIHO = "https://49c0ccff7276e28e55e9e82de4addd1d@o923049.ingest.sentry.io/6029559";
   private static long CRCOHICOHHHHROROHRCOICOCC = 0L;
   private static int OOOCICRCRROHIICRIOIHRRRHI = 0;

   public static void init() {
      Sentry.init((var0) -> {
         var0.setBeforeSend(CRHICIIOIIOIOIIOCOOICHCHC::RHORCRICRIIRHOIHOCRRORHCC);
         var0.setDsn(RHORCRICRIIRHOIHOCRRORHCC.HCORRHHRIRIRRRCRICCRRRHCO.equals("master") ? "https://49db0029d2304d69bd80986185f7fafd@o923049.ingest.sentry.io/6029559" : "https://49c0ccff7276e28e55e9e82de4addd1d@o923049.ingest.sentry.io/6029559");
         var0.setDebug(!RHORCRICRIIRHOIHOCRRORHCC.COROOCIICOHOCOOHCIIHORROR);
         var0.setEnvironment(RHORCRICRIIRHOIHOCRRORHCC.HCORRHHRIRIRRRCRICCRRRHCO.equals("master") ? "production" : RHORCRICRIIRHOIHOCRRORHCC.HCORRHHRIRIRRRCRICCRRRHCO);
         var0.setProguardUuid(RHORCRICRIIRHOIHOCRRORHCC.RCRRCORCRROHRRCRRCOHORHRC);
         String var1 = RHORCRICRIIRHOIHOCRRORHCC.HCORRHHRIRIRRRCRICCRRRHCO + "@" + RHORCRICRIIRHOIHOCRRORHCC.HCHOHICHCRRRHCORHHRIOCRHO;
         var0.setRelease(var1.replace('/', '_'));
         var0.setEnableUncaughtExceptionHandler(false);
         JsonElement var2 = OHCOOHIIHCCCCCORHIRIRCIOO.HOIHRCRIRCOOIOHCIRIRCOHIO.toJsonTree(HCRICIICRCIHCHIRHIIICIHCR(RIHRHOROOHHOIOCIOCOHCRCCI()));
         if (var2.isJsonObject()) {
            Iterator var3 = var2.getAsJsonObject().entrySet().iterator();

            while(var3.hasNext()) {
               Map.Entry var4 = (Map.Entry)var3.next();
               var0.setTag((String)var4.getKey(), ((JsonElement)var4.getValue()).toString());
            }
         }

         String var5 = OHCOOHIIHCCCCCORHIRIRCIOO.CCROHCORROIROICOHCCHHRCCH();
         if (!var5.equalsIgnoreCase("?") && !var5.equalsIgnoreCase("not supplied")) {
            var0.addTracingOrigin(OHCOOHIIHCCCCCORHIRIRCIOO.CCROHCORROIROICOHCCHHRCCH());
         }

         if (RHORCRICRIIRHOIHOCRRORHCC.HCORRHHRIRIRRRCRICCRRRHCO.equals("master")) {
            if ((Boolean)com.moonsworth.lunar.client.CHRCROHCCIRRCHIOICROIHCCI.HOICRIOOCRIOCCHCHROOOHCHH.RHORCRICRIIRHOIHOCRRORHCC.from("SentryTraceSampling").orElse(false)) {
               var0.setTracesSampleRate(0.05);
            }
         } else {
            var0.setTracesSampleRate(1.0);
         }

      }, true);
      com.moonsworth.lunar.ichor.HORRIIHRCCORRHCHRHHCCORCO.CRHICIIOIIOIOIIOCOOICHCHC.register((var0) -> {
         RHORCRICRIIRHOIHOCRRORHCC(var0, "Mixin Application");
      });
   }
`

**Comment by cubewhy** [comment]
已更新 https://github.com/CubeWhyMC/LunarAntiData/

**Comment by cubewhy** [comment]
有个地方写错了
