### ISSUE TITLE
路径识别不正确

### ISSUE THREAD

**Issue by Tr4velt0Here** [CubeWhyMC/LunarClient-CN#5]
理想效果
![image](https://user-images.githubusercontent.com/87561321/213909637-622d682e-f7f1-4377-8726-832eca86761a.png)
实际效果
![image](https://user-images.githubusercontent.com/87561321/213909650-2738a7ce-431b-47f1-90ad-e71b65b5ca3b.png)

**Comment by CubeWhyMC** [comment]
正在尝试修复这个，一会更新
